export default {
  0: {
    name: "user",
    hp: 100,
    att: 10,
    attSpeed: 4,
    speed: 800,
    axios: {
      top: 650,
      left: 250,
      width: 80,
      height: 80,
    },
    img: "./img/a.png",
    skill: 100,
    score: 100,
  },
  1: {
    name: "monster_easy",
    hp: 75,
    att: 15,
    attSpeed: 0,
    speed: 30,
    axios: {
      top: 10,
      left: 50,
      width: 50,
      height: 50,
    },
    img: "./img/b.png",
    skill: false,
    score: 100,
  },
  2: {
    name: "monster_normal",
    hp: 120,
    att: 30,
    attSpeed: 0,
    speed: 40,
    axios: {
      top: 10,
      left: 50,
      width: 80,
      height: 80,
    },
    img: "./img/c.png",
    skill: false,
    score: 300,
  },
  3: {
    name: "monster_normal",
    hp: 120,
    att: 30,
    attSpeed: 0,
    speed: 40,
    axios: {
      top: 10,
      left: 50,
      width: 80,
      height: 80,
    },
    img: "./img/c.png",
    skill: false,
    score: 300,
  },
};
